title: Mahalakshmi_Resume
logo: /assets/Maha.png
description: A freaking and positive attitude towards what I does it matters a lot to me.
show_downloads: true

# Configures the theme through the remote theme plugin
remote_theme: pages-themes/minimal@v0.2.0
plugins:
  - jekyll-remote-theme
